apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::828419607696:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::828419607696:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-4L8XZTNXCEG8
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-15T19:26:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1175"
  safelink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: cc204011-6440-4220-82fa-5508d6b1fa3a
